### ISSUE TITLE
run-regression-testコマンドの複数のオプションで任意のコマンドが実行できてしまう。

### ISSUE THREAD

**Issue by komainu8** [groonga/groonga-query-log#6]
run-regression-testコマンドの以下のオプションに、シェルが解釈可能なコマンドを含めると、そのコマンドを実行できてしまいます。

* --new-groonga
* --old-groonga

また、以下のように指定すると、回帰テストも成功のうえ、lsコマンドが実行されます。
例)
/usr/local/new_groonga/bin/groonga-query-log-run-regression-test --old-groonga=/usr/loca/od_groonga/bin/groonga --new-groonga=/usr/local/new_groonga/bin/groonga;ls -al

**Comment by kou** [comment]
バージョンはいくつですか？
masterだと次のようになって再現しませんでした。

```text
% ruby -I lib bin/groonga-query-log-run-regression-test --old-groonga="/tmp/local/bin/groonga;ls" --new-groonga="/tmp/local/bin/groonga;ls"  
/home/kou/work/ruby/groonga-query-log/lib/groonga/query-log/command/run-regression-test.rb:200:in `spawn': No such file or directory - /tmp/local/bin/groonga;ls (Errno::ENOENT)
	from /home/kou/work/ruby/groonga-query-log/lib/groonga/query-log/command/run-regression-test.rb:200:in `run'
	from /home/kou/work/ruby/groonga-query-log/lib/groonga/query-log/command/run-regression-test.rb:314:in `block in run'
```

**Comment by komainu8** [comment]
バージョンは、1.2.3です。
--old-groonga、--new-groongaの値を`"`でくくっていると思うのですが、`"`でくくらず、下記のように指定すると再現すると思います。
<pre>
--old-groonga=/tmp/local/bin/groonga;ls --new-groonga=/tmp/local/bin/groonga;ls 
</pre>

**Comment by kou** [comment]
そのときって、`groonga-query-log-run-regression-test`が`ls`を起動しています？
それとも、`groonga-query-log-run-regression-test`を実行しようとしているシェルが`ls`を起動しています？

**Comment by komainu8** [comment]
`groonga-query-log-run-regression-test`を実行しようとしているシェルが`ls`を起動しています。
したがって、この例だと、単にコマンドの連続実行として解釈されているだけのような気がしてきました。。。

以下のように指定しても`ls`は実効できますが、`groonga-query-log-run-regression-test`を実行しようとしているシェルが`ls`を起動しているので、これもspawn経由で実行されているわけではなさそうです。
--old-groonga="/usr/local/groonga_20170328/bin/groonga;\`ls\`"

なので、プログラムは問題ないかもしれません。すみません。もう少し検証してみます。

**Comment by komainu8** [comment]
検証の結果、私の早とちりでした。申し訳ございません。
本IssuesはCloseいたします。
